### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by e46mpwr**
Adding the text required for BrowerStack OSS Sponsorship.
https://www.browserstack.com/open-source

### CODE REVIEW

**Comment by yoshikiohshima** [comment]
What this is about?

**Comment by e46mpwr** [comment]
It's to get access to test Microverse using BrowserStack.  

BrowserStack loves Open Source
You move new ideas forward and make software better for everyone. Get lifetime access to test your open source project on 3000+ browsers and real mobile devices.

**Comment by yoshikiohshima** [comment]
It is great that they love open source. I have not found description that explains what they do when the repo has  "tested with BrowserStack" in README.

**Comment by e46mpwr** [comment]
Ah ok.  Here's the info from the email.

Hi,
​
Greetings of the day! We are happy you reached out!
 
To proceed with your sponsorship, please help us verify your ownership of the open-source project you would like to test. To do this:
 
1. Your project has to be at least 3 months old.
 
2. You will need to submit and merge a PR to the project. The PR has to add the following text to your readme.md file: “This project is tested with BrowserStack.”
 
3. The PR has to be dated post the date of your request for sponsorship.
 
Please send us the link to your PR after all the steps are completed. We will verify the approval points and activate your sponsorship accordingly.
 
Thank you for your understanding, and we look forward to getting you started on BrowserStack soon.

Regards,
Sheetal Pradhan.
BrowserStack Support

**Comment by yoshikiohshima** [comment]
Ok... Just to note, though, that to check if a client's project is crashing on some mobile devices, testing it at this upstream level here won't help, necessarily. If it is like having too many things in their world is the problem, setting up a test environment with those would be more direct way to figure out what is causing the crash.

**Pull request merged**
